services:
  protonmail-bridge:
    image: docker pull ghcr.io/moert09/protonmail-bridge-docker:build
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root
volumes:
  protonmail:
    name: protonmail
